### ISSUE TITLE
Tohle není issue xD

### ISSUE THREAD

**Issue by KakesRevengeCZ** [GravelCZLP/FarmBot#2]
Ahoj, 
tady Pavel ze Skypu, dřív jsme se bavili o modech etc, taky jsem je programoval, dej mi na sebe pls nějakej kontakt.

Dík

**Comment by GravelCZLP** [comment]
jindra.vese@gmail.com :) Email

**Comment by KakesRevengeCZ** [comment]
messenger nemáš? po emailu se blbě chatuje xD
